version: '3'
services:
  cardano-bridge:
    build:
      context: .
    container_name: 'cardano-bridge'
    ports:
      - '8080:8080'
    environment:
      - APPWRITE_URL
      - APPWRITE_PROJECT
      - APPWRITE_KEY
      - CARDANO_NETWORK
      - CARDANO_NODE_SOCKET_PATH
      - CARDANO_STORE
      - CARDANO_CONFIG
    volumes:
      - '/home/ubuntu/cardano/mainnet/ipc:${CARDANO_NODE_SOCKET_PATH}'
      - '/home/ubuntu/cardano/cardano-bridge/testnet/store:${CARDANO_STORE}'
      - '/home/ubuntu/cardano/cardano-bridge/testnet/config:${CARDANO_CONFIG}'
    restart: always
