name: function-sync-steam-actions-workflow
on:
  push:
    paths: 
     - "api/functions/sync-steam/**"
     - ".github/workflows/appwrite-function.yml"
    branches:
      - main

env:
  HOSTNAME: "api.badge.ar"
  APPWRITE_PROJECT: "badge-ar"

jobs:
  deploy-function-sync-steam:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: appwrite/setup-for-actions@v1
        with:
          endpoint: 'https://${{ env.HOSTNAME }}/v1'
          project: '${{ env.APPWRITE_PROJECT }}'
          key: '${{ secrets.APPWRITE_API_KEY }}'
      - name: Deploy function sync-steam
        run: |
          cd api && \
          appwrite functions createDeployment \
            --functionId='626611e29cfabd9b6f4c' \
            --activate=true \
            --entrypoint='./src/index.js' \
            --code='./functions/sync-steam'