name: cardano-bridge-actions-workflow
on:
  push:
    paths: 
     - "cardano-bridge/**"
     - ".github/workflows/cardano-bridge.yml"
     - "scripts/deploy-bridge.sh"
    branches:
      - main

env:
  SSH_CERTIFICATE: "${{ secrets.SSH_CERTIFICATE }}"
  DEPLOY_IP: "api.badge.ar"
  APPWRITE_KEY: "${{ secrets.APPWRITE_KEY }}"
  IPFS_KEY: "${{ secrets.IPFS_KEY }}"
  IPFS_SECRET: "${{ secrets.IPFS_SECRET }}"

jobs:
  deploy-bridge:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: "Checkout the files"
        uses: actions/checkout@v2

      - name: "Deploy cardano bridge on server"
        run: |
          # MULTI-LINE COMMAND
          # DEBIAN_FRONTEND=noninteractive sudo apt update -y
          # DEBIAN_FRONTEND=noninteractive sudo apt install -y openssh-server
          mkdir -p ~/.ssh
          echo -e "${{ secrets.SSH_CERTIFICATE }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          export DEPLOY_IP=${{ env.DEPLOY_IP }}
          export APPWRITE_KEY=${{ env.APPWRITE_KEY }}
          export COLLECTOR_ADDRESS=${{ env.COLLECTOR_ADDRESS }}
          export IPFS_KEY=${{ env.IPFS_KEY }}
          export IPFS_SECRET=${{ env.IPFS_SECRET }}
          ./scripts/deploy-bridge.sh