name: frontend-actions-workflow
on:
  push:
    paths: 
     - "frontend/**"
     - ".github/workflows/frontend.yml"
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: "Checkout the files"
        uses: actions/checkout@v2

      - name: Vercel Action
        uses: amondnet/vercel-action@v20.0.1
        with:
          vercel-token: "${ secrets.VERCEL_TOKEN }"
          project-name: badgedotar
          project-description: "badge.ar frontend"
          project-url: vercel.com/badgedotar/frontend
          vercel-args: '--prod' #Optional
          vercel-org-id: 8TnRdKG7AlD74ccBaEmZ0sGO #Required
          vercel-project-id: prj_fohMlx8xd57AOfLcW0glzWKihMFv #Required
          working-directory: frontend